### ISSUE TITLE
no darkmode and headers can be modified 

### ISSUE THREAD

**Issue by Shashwat0227** [samipak458/Simple-Library-Managment#10]
the  sign in buttons can be modified and hovering can be improved , and i can add a darkmode button to the site

**Comment by Shashwat0227** [comment]
please assign it to me

**Comment by samipak458** [comment]
Hi @Shashwat0227 thank you for creating issue.

You can improve sign in button and it's hovering. Dark mode issue assigned to someone else. If he failed then I will assigned to you.

You go ahead with with sign in button.

**Note: Don't forget to sync the fork.**

**Comment by Shashwat0227** [comment]
surely i will check out that sign in button , thanks :) i will try to do that before 4th or 5th oct

**Comment by Subhangi0707** [comment]
I want to work on this issue under hacktoberfest 2022
thanks!!

**Comment by Shashwat0227** [comment]
hey see i completed this assigned task , check it once and complete it from your end and synced the fork too

**Comment by Shashwat0227** [comment]
its 3 days and no dark mode is added , so can i add that too ?

**Comment by samipak458** [comment]
Sure go ahead @Shashwat0227

**Comment by samipak458** [comment]
Hi @Subhangi0707,

Kindly add dark mode.

**Comment by Shashwat0227** [comment]
should i add dark mode ? or footers ?

**Comment by samipak458** [comment]
@Shashwat0227 kindly fix error in previous PR.
@Subhangi0707 will work under this issue.

**Comment by Shashwat0227** [comment]
The hovering and all is working on my code only , which is on your site , how it is invalid then ? check once

**Comment by Subhangi0707** [comment]
kindly assign it to me!!

**Comment by Shashwat0227** [comment]
You kind of cheap , you dumb cheap guy
