### ISSUE TITLE
Update Header Section

### ISSUE THREAD

**Issue by sakshimishra19** [samipak458/Simple-Library-Managment#101]
Hello @samipak458 !
I want to update header section and also add some extra features to it.
Kindly assign this issue to me.

**Comment by samipak458** [comment]
Thanks for creating an issue @sakshimishra19 
Can you let me know what extra feature you're planning to add?

**Comment by sakshimishra19** [comment]
I want to add a sign up button in the Header section so that people can register themselves before adding a book and also want to remove the checkbox next to the search button which is not needed

**Comment by samipak458** [comment]
There is no sigin/sign-up functionality available currently. You can remove the checkbox and also edit search filters to filter.

**Comment by sakshimishra19** [comment]
ok

**Comment by samipak458** [comment]
@sakshimishra19 header is not fixed yet. Kindly fix it

**Comment by sakshimishra19** [comment]
Done

**Comment by PavvanPradeep** [comment]
can i work on this?

**Comment by samipak458** [comment]
It's already fixed @PavvanPradeep
