### ISSUE TITLE
Toggle button for favorite book

### ISSUE THREAD

**Issue by VighneshManjrekar** [samipak458/Simple-Library-Managment#103]
Toggle button can be more accurate or more user-friendly form control for the favorite book toggle. If you want to fix this issue kindly assign this to me I am willing to contribute on this

**Comment by VighneshManjrekar** [comment]
If you want to fix this issue kindly assign this to me I am willing to contribute on this

**Comment by samipak458** [comment]
Thanks for creating an issue @VighneshManjrekar.
Go ahead and fix it

**Comment by VighneshManjrekar** [comment]
@samipak458 can we use static image file for the heart logo? and thank you for assigning me this issue :)

**Comment by samipak458** [comment]
Kindly tell me in detail what are you planning to do @VighneshManjrekar. Also add screenshots that will be great.

**Comment by VighneshManjrekar** [comment]
Sure First I will replace checkbox with toggle button 
and can we use image file for logo instead of `&#9829` unicode

**Comment by VighneshManjrekar** [comment]
If it is out of the scope or not necessary I will only work on the toggle button enhancement

**Comment by VighneshManjrekar** [comment]
![image](https://user-images.githubusercontent.com/69366251/197331099-6e107b79-9f7d-47cc-b529-49b8603ff140.png)
is this fine?

**Comment by samipak458** [comment]
Yes, It looks good.
