### ISSUE TITLE
Link to social media 

### ISSUE THREAD

**Issue by Shaba1406** [samipak458/Simple-Library-Managment#110]
the linking of social media is not working. please assign this issue to me @samipak458

**Comment by samipak458** [comment]
@Shaba1406 you can work on it. If you want it is valid issue. Kindly reopen issue if you want to work.

**Comment by Shaba1406** [comment]
yes i want to work on this.

**Comment by samipak458** [comment]
Here you can find all my links of socials: 
[Social handles](https://linktr.ee/muhammadsamiullah)
[Facebook](https://www.facebook.com/sami.munir.3939)

**Comment by samipak458** [comment]
@Shaba1406 go ahead and create PR

**Comment by Shaba1406** [comment]
@samipak458 Can you please Share your instagram id as well.

**Comment by samipak458** [comment]
@Shaba1406  here is my [insta](https://www.instagram.com/sami_munir1/) id
