### ISSUE TITLE
Make another space/card for "Your Book Shelf" section

### ISSUE THREAD

**Issue by LeidiFlores** [samipak458/Simple-Library-Managment#119]
## Problem 

Currently on the page the _Your Book Shelf_ section looks like that

![image](https://user-images.githubusercontent.com/62189355/197368940-70b169ab-fddc-46f0-bc0e-25ed2f94fbfd.png)

I think needs space from the another section/card.

## Solution propose

Making a card for "Your Book Shelf" 

Please assign to me for help us with that for hacktoberfest

**Comment by samipak458** [comment]
Thanks for creating an issue @LeidiFlores 
Yes that will be great, go ahead @LeidiFlores

**Comment by LeidiFlores** [comment]
Thanks! I'm on it

**Comment by LeidiFlores** [comment]
hi! @samipak458 is ready here https://github.com/samipak458/Simple-Library-Managment/pull/125 :)
