### ISSUE TITLE
can add your about , twitter and other links at footer 

### ISSUE THREAD

**Issue by Shashwat0227** [samipak458/Simple-Library-Managment#12]
can add your twitter , discord , linkedin and all links at the bottom of the page

**Comment by ShivaRapolu01** [comment]
Is it part of hacktoberfest? If yes I am ready to contribute

**Comment by samipak458** [comment]
Thanks for creating issue @Shashwat0227.
Yes, you can add plain footer like in the center you can add @copy write and on right add links of linkedin, GitHub etc.

**Comment by samipak458** [comment]
Yes @ShivaRapolu01 it is a part of hacktoberfest.

**Comment by Shashwat0227** [comment]
> Thanks for creating issue @Shashwat0227. Yes, you can add plain footer like in the center you can add @copy write and on right add links of linkedin, GitHub etc.

can you add to a issue inside hacktober fest

**Comment by samipak458** [comment]
> > Thanks for creating issue @Shashwat0227. Yes, you can add plain footer like in the center you can add @copy write and on right add links of linkedin, GitHub etc.
> 
> can you add to a issue inside hacktober fest

Done

**Comment by adi-uchiha** [comment]
Can I submit a PR on this?

**Comment by Shashwat0227** [comment]
hey , if you can accept my pending PR , then i can work on this and create that , and please do send me your links which you want on the site

**Comment by M-Rahul1** [comment]
can I work on it. @samipak458 is it completed?
