### ISSUE TITLE
FAQ section

### ISSUE THREAD

**Issue by Shaba1406** [samipak458/Simple-Library-Managment#120]
I would like to add FAQ section for the website. Please assign this issue to me @samipak458

**Comment by samipak458** [comment]
That will be great @Shaba1406 
Can you explain how will you add that?

**Comment by Shaba1406** [comment]
I'm going to build its structure using html, CSS and java script. Html will include the documentation part, CSS will provide the look and javascript will make it responsive And for the documentation part, you can suggest to me what type of question and answers I have to add and if you wish, I can raise another PR for that as well.

here is the screenshot:- 

![Online Library - Google Chrome 23-10-2022 14_59_38](https://user-images.githubusercontent.com/97939567/197386134-74688736-c26f-426a-a421-fe3edbd36a35.png)

**Comment by samipak458** [comment]
Amazing @Shaba1406 nicely identified, there is a need of FAQs. 
Some of the questions, I have in mind:
Why do we use it?
Where does my books stored?
Can I edit my books?
Is it secured?
Is there any limit to store books?
How to contact us?
Not find your questions. Do mail your question at mail...
