### ISSUE TITLE
Too much blank space on page 

### ISSUE THREAD

**Issue by LeidiFlores** [samipak458/Simple-Library-Managment#126]
## Problem

On the page exists too much blank space, so looks like that

![image](https://user-images.githubusercontent.com/62189355/197415510-4a62b411-73b6-4c5b-80b9-4d02003b47f5.png)

## Proposed solution

Center the page on the content for a nice and clean look and feel.

Please assign me to help you and add a hacktoberfest tag

**Comment by samipak458** [comment]
Thank you for creating an issue @LeidiFlores 
Sure, go ahead

**Comment by LeidiFlores** [comment]
thanks! I'm on it :)

**Comment by LeidiFlores** [comment]
@samipak458 is ready here https://github.com/samipak458/Simple-Library-Managment/pull/127  :)!
