### ISSUE TITLE
can modify the tables

### ISSUE THREAD

**Issue by Shashwat0227** [samipak458/Simple-Library-Managment#13]

**Comment by samipak458** [comment]
@Shashwat0227 can you elaborate how will you modify table?

**Comment by Shashwat0227** [comment]
the table in the site is just dotted lines with no detailing can modify that and can fix all your buttons which are basic right now

**Comment by samipak458** [comment]
> the table in the site is just dotted lines with no detailing can modify that and can fix all your buttons which are basic right now

Both the issues are already created by other contributors if they failed then I will ask you to work on it.
