### ISSUE TITLE
nav-item

### ISSUE THREAD

**Issue by kalosFestus** [samipak458/Simple-Library-Managment#139]
Hello @samipak458 , the hover background-color does not cover the full text on hover and the nav-items are not rightly padded and positioned, I could work on it if changes are required, please assign this issue to me under hacktoberfest, thank you

**Comment by samipak458** [comment]
Go ahead @kalosFestus

**Comment by kalosFestus** [comment]
Thank you @samipak458 ,  please accept my PR under hacktoberfest I have done the changes according to the issue.

![nav-items adjusted](https://user-images.githubusercontent.com/79145625/198873981-48f66dff-4c47-4d9f-964b-8076d9fcd87f.png)

**Comment by samipak458** [comment]
Good job @kalosFestus 👍
