### ISSUE TITLE
Adding additional filters of search

### ISSUE THREAD

**Issue by DevilzzNikhil** [samipak458/Simple-Library-Managment#14]
I want to add features like search by author name book name or book type 
Please assign it to me @samipak458

**Comment by samipak458** [comment]
@DevilzzNikhil this issue is already created.

**Comment by DevilzzNikhil** [comment]
@samipak458  can u suggest some issues ??

**Comment by samipak458** [comment]
@DevilzzNikhil you have to wait as features are adding so you can improve their styling.
