### ISSUE TITLE
UI Improvements in Dark Mode

### ISSUE THREAD

**Issue by wardahabid03** [samipak458/Simple-Library-Managment#148]
Answers of frequently asked questions in dark mode are in grey color which is not readable. Similarly, h4 in footer are also not visible in dark mode. 
![croped](https://github.com/samipak458/Simple-Library-Managment/assets/117730126/bdb3e1df-346b-442f-a2e0-8e916557880b)

**Comment by wardahabid03** [comment]
I want to resolve this issue. Kindly assign this to me.

**Comment by samipak458** [comment]
Thank you for raising an issue @wardahabid03.
Go ahead and work in it.
