### ISSUE TITLE
Needs a space and a centered

### ISSUE THREAD

**Issue by rhnas110** [samipak458/Simple-Library-Managment#159]
Hi, Sir @samipak458 
Issue Description:
In the bottom section, elements are not tidy, I want the elements to have a space and centered.

Before:
![image](https://github.com/samipak458/Simple-Library-Managment/assets/51848196/58c17e33-28f4-43ee-b0ae-4b88766346ba)

After:
![image](https://github.com/samipak458/Simple-Library-Managment/assets/51848196/47863009-bac4-40d0-8751-f3b62651f5b7)

I think it looks better, can you take my advice and assign this task to me? and I'm actually new to open source contributions, I also participated in Hacktoberfest2023. Thanks for the response Sir @samipak458

**Comment by samipak458** [comment]
Go ahead @rhnas110
