### ISSUE TITLE
Preventing same books from being added multiple times

### ISSUE THREAD

**Issue by sumitbishti** [samipak458/Simple-Library-Managment#16]
Right now, books with same name, author and type can be added multiple times. Which increases redundancy!
I can work on this issue.

**Comment by samipak458** [comment]
Thanks for creating an issue @sumitbishti. 
Nicely identify, good job. You can start working on it.

**Comment by sumitbishti** [comment]
Ok thank you. I have already finished it. When can i submit a PR?
Do i need to create a separate branch for that?

**Comment by Aryan-Srivastava** [comment]
@sumitbishti yeah, you need to create a separate branch before working on the issue, don't commit on the main branch.
