### ISSUE TITLE
[BUG] Drop down button is not working properly

### ISSUE THREAD

**Issue by youtanimstar** [samipak458/Simple-Library-Managment#161]
Hi @samipak458 ,
While exploring your website, I noticed a small bug in the drop-down section. When I hover over the 'filter' dropdown, the options are displayed, but they become hidden when I move my cursor. Therefore, I believe I can fix this. Please assign this issue to me.
here is the bug 
![Untitled video - Made with Clipchamp (1)](https://github.com/samipak458/Simple-Library-Managment/assets/107903218/616e3f8c-93ec-4c6d-a059-3d08934fc9cc)

**Comment by samipak458** [comment]
Go ahead @youtanimstar

**Comment by youtanimstar** [comment]
> Go ahead @youtanimstar

Thank you for assigning this task to me. I will do my best. 😊
