### ISSUE TITLE
Adding a Edit book option

### ISSUE THREAD

**Issue by saimaheshtaduri** [samipak458/Simple-Library-Managment#17]
Now if we enter the book information incorrect, we have to remove it and add it again. Instead there could be a edit button, using which details can be updated instantly.

**Comment by samipak458** [comment]
Thanks for creating an issue @saimaheshtaduri. Nicely identify, great job. Go ahead and add this feature.

**Comment by Subhangi0707** [comment]
I would like to work on this issue under Hacktoberfest 2022
Thanks!!

**Comment by samipak458** [comment]
@Subhangi0707 this issue is closed now. Kindly create another issue.
