### ISSUE TITLE
Creating another type of book

### ISSUE THREAD

**Issue by diego-rapoport** [samipak458/Simple-Library-Managment#19]
I just made a very few changes to add a new type of book in my fork
![29-09-2022-23h12min45](https://user-images.githubusercontent.com/66575787/193175431-5a57668d-5a6d-496b-8c13-85cf3b00679a.jpg)

It also has a click management to toggle the input tag for all radio buttons and it will keep the type "Other" if you don't write anything inside the input. If this is an interesting feature, I'll be glad to make a PR.

**Comment by samipak458** [comment]
Thanks for creating an issue @diego-rapoport. It is an interesting feature. Go ahead and create PR.

**Note: Don't forget to sync the fork.**
