### ISSUE TITLE
Adding seperate log in spaces for the ADMIN and a NEW USER

### ISSUE THREAD

**Issue by maveraw** [samipak458/Simple-Library-Managment#21]
HEY ! 
So adding seperate workspace for an existing user will help them to manage their records and hence modify the previous changes. While, there will be new user who need to log in first to become a member. They will be able to see the already existing books so that they can save/add for themselves from the slot.  @samipak458

**Comment by samipak458** [comment]
Hi,
Thanks for creating an issue @maveraw. There is no database is connected, will you use database to save credentials?

**Comment by maveraw** [comment]
yes

**Comment by samipak458** [comment]
Ok, go ahead @maveraw.

**Note: Don't forget to sync the fork.**

**Comment by maveraw** [comment]
i m on it

**Comment by samipak458** [comment]
@maveraw any updates?

**Comment by maveraw** [comment]
@samipak458 hi buddy , sorry my exams were going on. I am resuming my work. Hopefully I will complete it today itself. So sorry for the delay.

**Comment by samipak458** [comment]
Sure sure
Try to do in October so that it will count in Hacktoberfest

**Comment by samipak458** [comment]
Any updates @maveraw
