### ISSUE TITLE
Adding read status in the library

### ISSUE THREAD

**Issue by nalin243** [samipak458/Simple-Library-Managment#23]
Another option can be added in the display telling us whether we have read that book @samipak458

**Comment by samipak458** [comment]
Hi,
Thanks for creating an issue @nalin243. Can you elaborate more like how will you implement it?

**Comment by nalin243** [comment]
![Screenshot_20221001_071943](https://user-images.githubusercontent.com/29351098/193378467-1030e87f-1bcb-4eb8-96dd-9e1c93f9d62e.png)



Something like this? I could also put a checkbox instead of Yes or No to make it editable. @samipak458

**Comment by samipak458** [comment]
Hi @nalin243,
Thank for creating an issue. You can go ahead and start working on it.

Yes, put a checkbox instead of Yes or No.

**Note: Don't forget to sync the fork.**
