### ISSUE TITLE
Adding a favorites section 

### ISSUE THREAD

**Issue by Aryan-Srivastava** [samipak458/Simple-Library-Managment#25]
![fav section book](https://user-images.githubusercontent.com/68139593/193338641-64d59de3-2298-4f86-bbc4-6276a113cf11.png)

**Comment by Aryan-Srivastava** [comment]
I want to add this feature as a participant, please do assign me this issue.

**Comment by samipak458** [comment]
Hi, thanks for creating an issue @Aryan-Srivastava. Is it clickable to add to favourites?
Isn't it better if you click on heart it add to new section **favourite**?

**Comment by Aryan-Srivastava** [comment]
A new section in sense, like a section containing only favs just like the general section ? Did I get it right ?

**Comment by samipak458** [comment]
Yes @Aryan-Srivastava

**Comment by samipak458** [comment]
**Note: Don't forget to sync the fork.**

**Comment by saimaheshtaduri** [comment]
@Aryan-Srivastava  are you working on this ?

**Comment by saimaheshtaduri** [comment]
I think, instead of having a separate column, the heart icon can be put in the bottom right of the name column itself. It could save a column as the table is already filled .

**Comment by Aryan-Srivastava** [comment]
On it, yeah it think so that will be a better thing to do
