### ISSUE TITLE
Navbar marquee logo issue

### ISSUE THREAD

**Issue by rezwancs** [samipak458/Simple-Library-Managment#28]
When we hover on the marquee logo "Online Library", on top-left side of the navbar, the height of the navbar increases. Can I please fix this issue?
![image](https://user-images.githubusercontent.com/30120066/193384471-df0b2f1c-03f2-4c46-9668-e618a1ad34d4.png)

**Comment by samipak458** [comment]
Hi @rezwan2525,
Thank for creating an issue. You can go ahead and start working on it.

**Note: Don't forget to sync the fork.**
