### ISSUE TITLE
Improvement of intro text design

### ISSUE THREAD

**Issue by rezwancs** [samipak458/Simple-Library-Managment#29]
Hi, this text doesn't have the same top and bottom padding, so it doesn't look vertically centered. 
Wouldn't it be nice if we keep the title vertically centered?
![image](https://user-images.githubusercontent.com/30120066/193384532-0208cea4-b944-490d-bf1b-40acae56e330.png)

**Comment by kushaljgec2025** [comment]
assign me the task i will try to fix it

**Comment by samipak458** [comment]
Hi @rezwan2525,
Thank for creating an issue. You can go ahead and start working on it.

**Note: Don't forget to sync the fork.**
