### ISSUE TITLE
I want to improve the design of webpage

### ISSUE THREAD

**Issue by dvig14** [samipak458/Simple-Library-Managment#3]
@samipak458.

**Comment by dvig14** [comment]
@samipak458 .kindly assign this to me.

**Comment by samipak458** [comment]
Hi @dvig14, 
Can you please elaborate, how will you improve the design of webpage? like are you planning to add gradients in bg or changing the style of adding book & book shelf sections?

By contributing to my repo your contribution will also count in HacktoberFest.

If you haven't register in HacktoberFest yet, so do register.
https://hacktoberfest.com/

**Comment by praveenscience** [comment]
Hey Sami, great shout-out to you in regards to Hacktoberfest, I just saw your repo that's been recently updated under JavaScript and there are going to be 100s of people participating in your repo! 👍 Thanks for all your good work! 🤗

**Comment by dvig14** [comment]
Hey , I will change the design by using css properties like box shadow and
more some changes making the website attractive.

**Comment by samipak458** [comment]
Ok @dvig14, 
I'm assigning you this issue, you can now start working on this issue.

**Comment by dvig14** [comment]
Thanks a lot. 😊

**Comment by samipak458** [comment]
> Hey Sami, great shout-out to you in regards to Hacktoberfest, I just saw your repo that's been recently updated under JavaScript and there are going to be 100s of people participating in your repo! 👍 Thanks for all your good work! 🤗

Hi @praveenscience sir,
Oh wow amazing 🤩
Thank you so much sir, you help me a lot in my journey.

**Comment by Petsamuel** [comment]
I'm interested on working on this issue

**Comment by samipak458** [comment]
Hi @Petsamuel, 
This issue is resolved by diksha. You can create any other issue. thank you.

**Comment by Shashwat0227** [comment]
hey , saw your website , i think i can improve it by adding some more hover effect and by improving the search button and the navigation bar , and you can add more stuff to that like dark mode and other things , if you can assign me this i will  try to improve it more by adding darkmode by one click and other headings with css styling

**Comment by samipak458** [comment]
@Shashwat0227 create new issue
