### ISSUE TITLE
Website contents is visible on navbar

### ISSUE THREAD

**Issue by rezwancs** [samipak458/Simple-Library-Managment#30]
Hi, when we scroll on the website, we can see website content on the navbar. I am just curious if it is intentionally designed that way. If not, can we please fix that ? 
![image](https://user-images.githubusercontent.com/30120066/193385636-b31ce548-6d70-4431-9ab6-280b28371f9c.png)

**Comment by samipak458** [comment]
hi @rezwan2525,
it designed like that.

**Comment by sumitbishti** [comment]
> hi @rezwan2525, it designed like that.

Well, in my opinion it doesn't give a good look. It looks more of a bug then a design. 
Plus it serves no practical purpose. Feel free to correct me, if I'm wrong.

**Comment by samipak458** [comment]
I appreciate your opinion. Do you want to improve it?

**Comment by rezwancs** [comment]
@samipak458 Please assign this ticket to me.

**Comment by sumitbishti** [comment]
> I appreciate your opinion. Do you want to improve it?

Well, we can just make it non-transparent and it would be just fine. If you want it i can do that.
