### ISSUE TITLE
Add Publication Date of Book, ISBN number of book and  Edition of Book

### ISSUE THREAD

**Issue by nileshlad09** [samipak458/Simple-Library-Managment#33]
There should be two more Inputs for getting the Publication Date or ISBN number of book Because there are many books can containing the similar type of names so it is easy to find out which book we want by seeing the publication date of the book,
and another input for the edition of the book because there can be many editions available for a similar book

This data is helpful for users to get the right book they want.

**Comment by nileshlad09** [comment]
![image](https://user-images.githubusercontent.com/89249015/193405420-e729d591-fc6e-4f94-8be7-63e1d557485d.png)

![image](https://user-images.githubusercontent.com/89249015/193405462-ac939662-9c2b-4058-bd8d-8e219d64320d.png)

**Comment by samipak458** [comment]
Hi @nileshlad09,
thank you for creating an issue. You can go ahead and work on it.

**Comment by samipak458** [comment]
**Note: Don't forget to sync the fork,**
