### ISSUE TITLE
[Bug] There is still a way to add duplicate "other" type books !!

### ISSUE THREAD

**Issue by sumitbishti** [samipak458/Simple-Library-Managment#40]
There are still some bugs left, and some new ones have occurred after new contributions, like book types are in lowercase letters, etc.
![Screenshot (33)](https://user-images.githubusercontent.com/75713174/193457167-2efa240b-b6c9-47c9-a5a6-e17fd963c59f.png)

**Comment by sumitbishti** [comment]
I have correctly identified, and fixed some of them, if you allow I can create a new PR.

**Comment by samipak458** [comment]
Ok, go ahead and fix it @sumitbishti
