### ISSUE TITLE
Adding Background and Footer

### ISSUE THREAD

**Issue by ghost** [samipak458/Simple-Library-Managment#44]
I'll add background to the body and improve the footer section by adding about, support, social media links, and experience to make it stand out.

Here is the background preview for the body
![image](https://user-images.githubusercontent.com/80773310/193467855-ab08054c-be36-4f52-b7c3-6fe7cd573fd0.png)

Here is the footer section
![image](https://user-images.githubusercontent.com/80773310/193467867-eee719cf-48a9-4e88-9ea7-627df795d77c.png)

What do you think?
If it suits you, please assign me, and I have coded it.

**Comment by samipak458** [comment]
It's also great, can you give background some how same to footer ?

**Comment by ghost** [comment]
Is this good enough?

![image](https://user-images.githubusercontent.com/80773310/193494146-6311a04d-6eca-400d-b0f7-ccec90a06a59.png)

The clear shelf button looks misplaced, though; I can't figure out how to fix it.

**Comment by samipak458** [comment]
Do first one that's look really great. Sure, fix it.

Go ahead and start working on it.

**Comment by ghost** [comment]
Found a way to connect the background body and footer.
What do you think?
![image](https://user-images.githubusercontent.com/80773310/193501333-04c7899b-97ee-415f-8322-1a350133b60f.png)

**Comment by samipak458** [comment]
That's look awesome @DHCJS , kindly implement it. One more thing make it responsive as well.

**Comment by ghost** [comment]
Before
![image](https://user-images.githubusercontent.com/80773310/193722728-8c7b2d59-5125-455e-963d-d970559febea.png)
![image](https://user-images.githubusercontent.com/80773310/193722783-feb1ca82-89a3-4abc-b70b-163f6b5cce71.png)

After
![image](https://user-images.githubusercontent.com/80773310/193722644-d630594f-d11f-4632-aee1-31049916f6e2.png)
![image](https://user-images.githubusercontent.com/80773310/193723230-7ee84d7b-e609-4047-bd69-64013fa91117.png)

Added slight move to the right and for the links, it will only turn blue if we hover to it with a pointer cursor to make it noticeable.

Is it okay to make PR now @samipak458 ?
