### ISSUE TITLE
Improve the navbar design

### ISSUE THREAD

**Issue by AtriSukul1508** [samipak458/Simple-Library-Managment#45]
The design of the navbar can be upgraded

**Comment by AtriSukul1508** [comment]
I would like to work on this issue

**Comment by samipak458** [comment]
Ok, go ahead @AtriSukul1508 

Don't forget to sync the fork

**Comment by samipak458** [comment]
@AtriSukul1508 kindly fix search bar as well.

**Comment by AtriSukul1508** [comment]
what's the problem with the search bar?

**Comment by samipak458** [comment]
If you click on search bar page refresh.
