### ISSUE TITLE
add book urls and also the status of that book 

### ISSUE THREAD

**Issue by saimaheshtaduri** [samipak458/Simple-Library-Managment#48]
I think it will be good, if ppl are able to store the url of the book. Thus on clicking the book, they will be able to read it online then and there it self. The status of the book ( if possible the page no where they stopped reading ) will also be useful.

**Comment by samipak458** [comment]
Ok you can work on this issue but you also have to make book shelf responsive.

**Comment by samipak458** [comment]
I will assign once you acknowledge @saimaheshtaduri

**Comment by saimaheshtaduri** [comment]
Will do it @samipak458

**Comment by saimaheshtaduri** [comment]
new idea : I think, there should be a **finished** button, on clicking, the book has to move to other section or just a finished tag attached to it.

**Comment by saimaheshtaduri** [comment]
@samipak458  can I start working on this ?

**Comment by samipak458** [comment]
Sure, go ahead @saimaheshtaduri

**Comment by saimaheshtaduri** [comment]
I will make these changes : 
- add a url input in the add book form.
- On clicking the book title in table, the corresponding url opens.
- will make a **finished** toggle button, if its on, that means, the book is finished reading.

@samipak458  please check them once. I will start working.
