### ISSUE TITLE
Preloader for the website 

### ISSUE THREAD

**Issue by YashBawa** [samipak458/Simple-Library-Managment#51]
A preloader looks cool during the loading time of a website.

**Comment by YashBawa** [comment]
@samipak458 please assign me this issue as I want to work on it. To bring a better look for the website.
Thank you.

**Comment by YashBawa** [comment]
@samipak458 can I start working on this issue?

**Comment by samipak458** [comment]
Sure, go ahead @YashBawa

**Comment by YashBawa** [comment]
Thanks, @samipak458 will go ahead with it.
