### ISSUE TITLE
Mobile Responsive!

### ISSUE THREAD

**Issue by sarthakastic** [samipak458/Simple-Library-Managment#53]
The site is not mobile responsive.
Navbar and books table are not responsive. It's overflowing in x axis.

**Comment by samipak458** [comment]
Go ahead and fix it @sarthakastic

**Comment by samipak458** [comment]
@sarthakastic also make the navbar responsive

**Note: Don't forget to sync the fork.**

**Comment by sarthakastic** [comment]
sure. 
Could u also add the hacktoberfest-accepted label?

**Comment by samipak458** [comment]
I will add that label on PR. Kindly make the PR @sarthakastic
