### ISSUE TITLE
bug: dark mode button toggle issue and improve dark mode design

### ISSUE THREAD

**Issue by saimaheshtaduri** [samipak458/Simple-Library-Managment#54]
Issues I encountered : 
- The dark mode button icon is not toggling well. 
- The nav bar is not so attractive, the search bar could be a bit longer
- In dark mode, date icon isn't visible
- There is no validation for ISBN number input field
- improve fonts and colors

**Comment by samipak458** [comment]
Go ahead and fix it @saimaheshtaduri
