### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by saimaheshtaduri** [samipak458/Simple-Library-Managment#55]
As new features and functionalities have come, I think the readme should be updated too

**Comment by samipak458** [comment]
Thanks for creating an issue @saimaheshtaduri. Go ahead.

**Comment by koder-aritra** [comment]
I would like to work on this issue.Can you assign it to me?

**Comment by samipak458** [comment]
@koder-aritra I will assign you tomorrow if @saimaheshtaduri not reply.

@saimaheshtaduri are you working on this issue or not?

**Comment by saimaheshtaduri** [comment]
yes,I am. I will raise pr by tomorrow

**Comment by jyotika6221** [comment]
If the issue is not resolved yet, plz assign me this task.

**Comment by theshubhamgour** [comment]
I would like to work on this issue.Can you assign it to me? @samipak458

**Comment by samipak458** [comment]
Ok @saimaheshtaduri

**Comment by samipak458** [comment]
@theshubhamgour and @jyotika6221 @saimaheshtaduri is already working on it. You guys can contribute to web storage.md or Azure static web app.md.

**Comment by theshubhamgour** [comment]
@samipak458 Please help with the directory link where we need to update the readme.md files

**Comment by samipak458** [comment]
@theshubhamgour Here are the links:
[Azure Static Web Apps](https://github.com/samipak458/Simple-Library-Managment/blob/main/Azure%20Static%20Web%20Apps.md)
[Web Storage](https://github.com/samipak458/Simple-Library-Managment/blob/main/Web%20Storage.md)
