### ISSUE TITLE
Adding a custom book type.

### ISSUE THREAD

**Issue by saimaheshtaduri** [samipak458/Simple-Library-Managment#56]
When user selects other, a input should appear where they can type the book type. This could be useful coz very few types are mentioned.

**Comment by samipak458** [comment]
Go ahead and fix it @saimaheshtaduri

**Comment by saimaheshtaduri** [comment]
@samipak458  I see the custom type feature is already implemented, but I encountered a major bug i.e. **add book** isn't working. and I figured out why. Can I just raise a PR directly solving that issue ?

**Comment by samipak458** [comment]
Close this one and create new issue before creating PR .
