### ISSUE TITLE
Adding a Heading and Fix Typo

### ISSUE THREAD

**Issue by ghost** [samipak458/Simple-Library-Managment#6]
Hi there,

I wanted to add another heading for the first section. So after Welcome To Online Library, another title will make it straightforward for another area.
![image](https://user-images.githubusercontent.com/80773310/192812546-784d5740-716c-4f77-b20d-a831ddcd1518.png)

and the second, I want to change the first letter of this box into uppercase instead of lower case
![image](https://user-images.githubusercontent.com/80773310/192812941-0a03ed38-696e-47f0-ac7b-b729cc834967.png)

I think I might a little bit of help too if you are willing to help me in this case to make a pull request.

Thank you!

**Comment by Petsamuel** [comment]
Assign this issue to me

**Comment by YashBawa** [comment]
Hello @DHCJS ,
I would like to work on this issue under hacktoberfest tag. Can u please assign it to me.

**Comment by samipak458** [comment]
Hello @DHCJS,

Thank you for creating issue.

Can you tell me what will be another heading for the first section? Can you name it?

Second issue is fine. 

Sure I will help you out in making PR.

**Comment by DHCJS** [comment]
> Hello @DHCJS ,
> 
> I would like to work on this issue under hacktoberfest tag. Can u please assign it to me. 
> 
> 

Sorry bro, I am gonna assign the PR for myself.

**Comment by ghost** [comment]
> Can you tell me what will be another heading for the first section? Can you name it?

How about "Add a Book" for the heading?

Please assign this issue to me to make a PR if it is okay. Thank you!

**Comment by samipak458** [comment]
Ok, go ahead @DHCJS .

**Note: Don't forget to sync the fork.**

**Comment by ghost** [comment]
Additionally, I want to create a Folder for easier management in the Code editor.
Maybe a folder that for HTML and CSS and JavaScript itself.

**Comment by samipak458** [comment]
Assets folder, right?

**Comment by ghost** [comment]
Right, maybe that's what it's called. So we will create a file for ourselves inside the folder.

Right now, when I open VS code, it only tells me to select a language.

I used to have a folder, and later, I created a file in it. It is a new experience, but hopefully, I will manage to do it correctly.
