### ISSUE TITLE
Adding More Option.

### ISSUE THREAD

**Issue by maharshi-sinha** [samipak458/Simple-Library-Managment#7]
Want to add anime to the site.

**Comment by maharshi-sinha** [comment]
Kindly assign it to me!

**Comment by samipak458** [comment]
Hi @maharshi-sinha,
Thanks for creating an issue. You can add "anime" but can you make some changes in CSS as well?

**Comment by maharshi-sinha** [comment]
Yeah! Thinking off!

**Comment by samipak458** [comment]
Ok great. Go ahead.
**Note: Don't forget to sync the fork.**

**Comment by Shashwat0227** [comment]
hey , i have learned html and css and can add and style the options too , you can assign it to me
