### ISSUE TITLE
Search Text not visible + Improve Dark Mode toggle

### ISSUE THREAD

**Issue by soustab10** [samipak458/Simple-Library-Managment#72]
Search Bar text not visible due to poor contrast:
![image](https://user-images.githubusercontent.com/95632583/194573521-569d6589-b5e8-4826-8dfe-ca5edaf70826.png)

Improve dark mode toggle to this:
![image](https://user-images.githubusercontent.com/95632583/194573697-6f57a942-96f8-472e-a3e9-24c615aaf182.png) 
![image](https://user-images.githubusercontent.com/95632583/194573783-5bcf2297-e262-4233-837f-9f7ac59d6433.png)

Add an icon to the webpage:
![image](https://user-images.githubusercontent.com/95632583/194573917-2cf4aafa-944c-41f2-b26b-b88c4d6269fe.png)

I am willing to do all the above changes. Please assign this issue to me. Thank you.

**Comment by samipak458** [comment]
Ok, go ahead @soustab10
