### ISSUE TITLE
Add the count of Stars and Forks of the repo in the footer section of the website

### ISSUE THREAD

**Issue by koder-aritra** [samipak458/Simple-Library-Managment#76]
I would like to add the count of the stars and forks of the repo in the footer section of the website.

**Comment by samipak458** [comment]
Ok go ahead @koder-aritra

**Comment by samipak458** [comment]
@koder-aritra any updates?

**Comment by samipak458** [comment]
Are you working on it @koder-aritra ?

**Comment by deepaksuthar40128** [comment]
can you assign it to me
