### ISSUE TITLE
Social links are empty 

### ISSUE THREAD

**Issue by AnshuPathak-88825** [samipak458/Simple-Library-Managment#79]

**Comment by AnshuPathak-88825** [comment]
I wanna add all the social link in social icons pls assign me this issue @samipak458

**Comment by samipak458** [comment]
Hi @AnshuPathak-88825,
Thanks for raising the issue but I don't think this is valid issue. Can you make website responsive?

**Comment by AnshuPathak-88825** [comment]
ok I'm closing it I'll raise another issue for that
