### ISSUE TITLE
Adding dark mode to the website 

### ISSUE THREAD

**Issue by YashBawa** [samipak458/Simple-Library-Managment#8]
Adding a dark styling for the dark mode makes the website look even better in two different modes.

**Comment by YashBawa** [comment]
Hey @samipak458 , can u please assign me this issue under hacktoberfest . 
Thanks !!

**Comment by samipak458** [comment]
Thanks for creating an issue @YashBawa. That would be great, go ahead.

**Comment by YashBawa** [comment]
Thank you for assigning it, will start working!!

**Comment by Shashwat0227** [comment]
hey i can add dark mode to the site and can fix it , can you assign it to me?

**Comment by Subhangi0707** [comment]
I want to work on this issue under Hacktoberfest 2022
Thanks!!

**Comment by YashBawa** [comment]
@Subhangi0707 and @Shashwat0227 currently am working on it . Thanks .

**Comment by samipak458** [comment]
@YashBawa what's update? you haven't created PR yet.

**Comment by YashBawa** [comment]
Hey @samipak458 , yaa sorry, got stuck with some work, will be creating pr by today itself.

**Comment by YashBawa** [comment]
@samipak458 updated with Dark mode and created PR please verify and review it. Sorry for the delay.

**Comment by YashBawa** [comment]
Merged PR link :- https://github.com/samipak458/Simple-Library-Managment/pull/50#event-7509986542
