### ISSUE TITLE
I will fixed navbar design issue

### ISSUE THREAD

**Issue by DEV-Dhruva** [samipak458/Simple-Library-Managment#84]
![image](https://user-images.githubusercontent.com/94905683/195031163-15fe48d3-3dc4-45ba-b5ee-6ba16e587999.png)
Navbar is transparent, which causes text to show behind it.
This can be fixed by changing opacity of navbar.
Please assign this issue to me

**Comment by samipak458** [comment]
Ok, go ahead @DEV-Dhruva
