### ISSUE TITLE
Text isn't visible in dark theme

### ISSUE THREAD

**Issue by AnshuPathak-88825** [samipak458/Simple-Library-Managment#88]

**Comment by AnshuPathak-88825** [comment]
pls assign me this issue

**Comment by samipak458** [comment]
Kindly add screenshot of the issue @AnshuPathak-88825

**Comment by samipak458** [comment]
@AnshuPathak-88825 ?

**Comment by AnshuPathak-88825** [comment]
Dude your website completely destroyed
![image](https://user-images.githubusercontent.com/78332454/196014288-9986f9f3-22a7-48c5-b5ef-c499d8e76be9.png)

**Comment by samipak458** [comment]
Kindly fix it @AnshuPathak-88825 
Make it responsive.
Don't forget to add Screenshots in PR.
Note: don't forget to sync the fork

**Comment by AnshuPathak-88825** [comment]
I'm creating another that is all about to revert website in last fixed version
