### ISSUE TITLE
Adding filter/sort feature

### ISSUE THREAD

**Issue by RichardHanitio** [samipak458/Simple-Library-Managment#9]
Hi, would it be nice if we add filter/sorting feature in "Your Book Shelf" section?

If you agree, please kindly assign it to me, thank you!

**Comment by samipak458** [comment]
Hi @RichardHanitio thanks for creating an issue.

Filter/sorting is already done by search bar, do you want add additional filter feature? Kindly elaborate.

**Comment by RichardHanitio** [comment]
Yes, I'm thinking of combining the search bar with a filter dropdown, to make it clear what the user's looking for.
For instance, a user may type in "pro" but refer to an author's name, not book name or book type.

**Comment by samipak458** [comment]
That will be great. Go ahead.
