### ISSUE TITLE
Footer design

### ISSUE THREAD

**Issue by tejus0** [samipak458/Simple-Library-Managment#99]
Hey @samipak458 I just saw your amazing website. The design is good but the footer is not developed well. So I want to contribute in your footer and make it more attractive. Can you please assign this issue to me? ![Screenshot_2022-10-22-08-39-16-027_com.android.chrome.png](https://user-images.githubusercontent.com/76488943/197316537-066d986c-18ed-4a9d-b4d7-4c6ece36c1c5.png)

**Comment by samipak458** [comment]
Sure, go ahead @tejus0 and don't forget to add Screenshots in pull request.

**Comment by Ishikasaraf20** [comment]
hey @samipak458 can you assign this issue to i can work on it

**Comment by tejus0** [comment]
Yes @samipak458 you can assign this issue to her. As I am really busy on some other tasks for a while.

**Comment by samipak458** [comment]
@Ishikasaraf20 go ahead and fix the footer design

**Comment by PavvanPradeep** [comment]
can i work on this

**Comment by samipak458** [comment]
@Ishikasaraf20 updates?

**Comment by Ishikasaraf20** [comment]
yes  @samipak458 making a PR's just a minute

**Comment by Ishikasaraf20** [comment]
hey @samipak458 i've made the footer kindly reveiw the changes and if you find this helpful kindly merge it your main branch just check your PR

**Comment by samipak458** [comment]
Kindly add screenshots @Ishikasaraf20

**Comment by Ishikasaraf20** [comment]
Here it is if you find this helpful  please merge it your main branch @samipak458 
![Screenshot from 2022-10-26 11-43-52](https://user-images.githubusercontent.com/88148077/197948705-5f644f17-d4e3-4c81-a45f-b6a2bb97dbea.png)

**Comment by samipak458** [comment]
Also add screenshots in mobile view @Ishikasaraf20 and also create the PR.
